### ISSUE TITLE
License information missing & is there some work going on?

### ISSUE THREAD

**Issue by stnmtz** [LedgerDomain/did-webplus#17]
Hi,

we're currently evaluating the best DID method to use in order to support DIDs within our open-source project based on a central approach. Thus, we would have different digital identities behind a web-server hosting DID Documents. did:web has too many flaws in our view and did:webs seems to be somewhat overcomplicated. We stumbled upon did:webplus and the approaches herein fit quite well to our requirements.

However
- All did:web enhancements don't seem to be "production-ready" (I would go as far and say this is true for did:web also).
- We would love to try out your examples and sources, but we're missing a license information within this repo, blocking us to try out your implementation and build integrations on top of it. (For us, open-sourcing this repo under an MIT-compliant license would be best)
- As the last commits and actions of this repo happened a while ago, we would like to inquire if this repo is still active and will sometime provide "production-ready" code?
  - If yes, we might be interested to contribute and would love to have a private chat about that
  - If not, would it be possible to fork, use and maintain parts of your work for another DID Method? (see license point above)

Additionally, we have one question with regards to the DID document's `selfSignature`: Multi-signing a DID document with different keys is so far not possible with this approach, correct?

Thanks and Best Regards,
Thomas

**Comment by vdods** [comment]
Thanks for your comments, Thomas.

It's fair to say that did:webplus is not yet production ready, so far only being a working demonstration of the data model, including mocks of the VDR and VDG (Verifiable Data Gateway).  The hiatus in development was due to my taking a sabbatical, but will resume shortly, with the goal of creating a production grade implementation.

Good call on the licensing, I'll get that added shortly.

I'd love to chat about collaborating -- can you email me at victor.dods@ledgerdomain.com and we can set that up?

Currently only a few single-signature methods are supported.  In principle, multi-sig should be possible, but I don't know much about how they work to comment further.

**Comment by vdods** [comment]
MIT License added.
