### ISSUE TITLE
On trust and the underlying issues

### ISSUE THREAD

**Issue by strumswell** [LedgerDomain/did-webplus#2]
I just read through your proposal and to break it down to it's core, I understand you are basically proposing a linked list of historic DID documents in a centralized place. You call that a microledger. The historic changes might be signed by a then valid key inside that old DID document.

You write a "[...] microledger is intended to be immutable [...]", which it inherently is not because you say later: "It is possible for a non-root DID document to be altered, but it requires the VDR sysadmin and the DID controller to collude.". Without signatures being created for each DID document update, illegal branching is only protected by somehow getting two differing signatures pointing to the same versionId. In theory, a rogue VDR owner could create a shadow branch that they use for, e.g., issuing their own VCs in an environment where nobody would even be able to get two differing signatures pointing to the same versionId. One could even say the the VDR owner and the DID controller are almost always the same underlying entity, which is the company that owns the domain used in the DID string. In a cloud wallet environment, where the VDR owner handles DID documents for their customers will also have control over their keys, making it possible for the VDR to create shadow branches or even rewrite history. Rewriting the history might also be something where a rogue VDR owner and a rogue DID controller might work together to forge audit history that is being used for law enforcement purposes.  

Ignoring the above, signed DID document updates are a minimum requirement for this DID method to be even feasible. Looking at possibly using this DID method in the future, each DID resolving *has to include a full history verification, which complexity grows linearly with the amount of versions.* This adds considerable amount of latency because with every VC verification, a wallet has to do the following without even having started to verify the VC:
- Request every DID document version starting from the root document
- Verify the correct hash linkage between the documents
- Verify each DID documents signature with a key from the previous DID document
So wallets would have to start caching the history of the DID documents they interact with, while the first resolving of a not-seen before DID *will* still take long. 

At the end of the day, you are trying to solve an issue that has already been solved in a better way by many other blockchain-based DID methods.

**Comment by vdods** [comment]
Thanks for your comments, Philipp.

I think I need to make it more prominent that `did:webplus` is meant to be somewhere in between `did:web` and e.g. `did:ethr` (this is mentioned in the "comparison" section, which is toward the bottom of the readme).  `did:webplus` is meant to serve a use case which is averse to cryptocurrency-based DID methods -- a use case relevant to government and other conservative industries.  To be fair though, not all blockchains are cryptocurrency-based.

There are three problems for which a gateway service, which pre-emptively mirrors and verifies the contents of a set of did:webplus VDRs, would provide solutions.
1. This would make alterations to or branching of DID histories more readily detectable and less feasible.  Not impossible, admittedly, but in many of the highly regulated industries that `did:webplus` is intended for (e.g. healthcare), the legal and financial penalties for intentional fraud of this level would be severe.
2. The pre-fetching+validating of DID microledgers would address the linear complexity of first-time DID resolution for those using the gateway.  Furthermore, because the gateway would do all DID microledger verification, this leaves the possibility for "thin clients" whose DID resolution process looks more like the plain HTTP GET for `did:web`.  This is analogous to the use of an ethereum gateway to which verification of the `did:ethr` contract is outsourced.
3. This would address the service availability problem that Chris Wirrig often points to, in that the VDR doesn't have to be online (or even remain in existence, in the case of historical audit) for DID resolution to still function.

Regarding the specific point about a single entity owning a VDR and cloud wallet -- I agree.  I think a VDR should be hosted by a neutral, 3rd party service provider whose business interests are aligned with faithfully executing the role of such a service provider.  A cloud wallet is already a practical compromise away from actual self-sovereign identity -- one has outsourced control of their private keys and therefore DIDs to a 3rd party which they implicitly trust.  This is why I personally prefer edge wallets, as they actually affect self-sovereign identity.

As an aside, I'm interested in the local caching and verification of the DID microledger, combined with the requirement of using the `hl` query param when using the DID to sign, as it will allow fully offline DID resolution and signature verification for DIDs that have already been cached (including historical resolution+verification).  Obviously determining if a particular DID document is the latest DID document requires a query to the appropriate VDR or gateway, but that's a separate consideration from the raw mechanics of resolution+verification against a particular DID document.  This offline capability has the benefit of speeding up DID resolution and signature verification for DIDs that have already been cached.

**Comment by alexcolganLD** [comment]
Within the pharmaceutical supply chain, as well as in other highly regulated industries, we have the sense that familiar "fit for purpose" tooling will allow stakeholders (such as software security experts and IT leaders) to speak with greater confidence about the mechanisms and protections involved.

**Comment by bumblefudge** [comment]
In terms of prior art, there are also blockchain-free systems which also have centralized witness structured NOT bound to a specific DLT/ledger:
https://web.plc.directory/
Who was it that said a ledger is just a centralized source-of-truth accessed through variably-trustless clients called nodes...

**Comment by vdods** [comment]
This is addressed by the witnessing schemes described in https://github.com/LedgerDomain/did-webplus#long-term-non-repudiability-via-witnessing-schemes and in particular, the proposed Verifiable Data Gateway.
